version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=meliapadb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
#  spring-boot-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - POSTGRES_NAME=meliapadb
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_HOST=db
#    depends_on:
#      - db
